### ISSUE TITLE
Add Bedrockify support

### ISSUE THREAD

**Issue by Slooshie1** [TurtleArmyMc/Panorama-Tweaker#1]
https://user-images.githubusercontent.com/90230538/150681151-c5dd5baf-c6dd-494a-bd08-ca92dd2e2187.mp4

**Comment by TurtleArmyMc** [comment]
I'm assuming you're using the Vistas mod, which replaces the default panorama with its own, which this mod doesn't affect. Assuming that's what's going on, I'll look into adding compatibility with Vistas, but it'll take a while. For now you'll just have to choose between the two mods.

**Comment by Slooshie1** [comment]
> I'm assuming you're using the Vistas mod, which replaces the default panorama with its own

I'm not using Vistas. I previously had it installed, but I since have deleted it (as it didn't work for me). The current panorama in the background is just a resource pack

**Comment by Slooshie1** [comment]
You can also see that I did not have it enabled during the time I recorded this video. For a very brief moment I had the Mod Menu screen open, and there were no mods between ToroHealth and WorldEdit, where Vistas would have been

**Comment by TurtleArmyMc** [comment]
Does the mod work if no other mods are installed?

**Comment by Slooshie1** [comment]
Yes
Well, I guess it's time to start Thanos-ing my mods to see which one causes the problem

**Comment by Slooshie1** [comment]
Found it

"BedrockIfy" makes it so that the menu panorama is visible on all menus (along with many many other features), so that's what causes the panorama to be stuck at its normal speed, angle, etc. Any looking into making these two mods compatible would be greatly appreciated. In the meantime, I will create an issue thread on BedrockIfy's github page.

**Comment by TurtleArmyMc** [comment]
I'll look into trying to fix it from my end.

**Comment by Slooshie1** [comment]
MC crashes when bedrockify and panorama tweaker are active in 1.19. They were working together perfectly in 1.18.2
